### ISSUE TITLE
Make

### ISSUE THREAD

**Issue by Naraku86** [CodigoLasagna/Hello-World-Engine#1]
Hola, no esta funcionando el make

Cuando ejecuto me sale los siguientes errores.

`g++ -lncurses -lpanel -o main HelloWorldEngine.o main.o
/usr/bin/ld: HelloWorldEngine.o: en la función `Renderer::Renderer()':
/home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:37: referencia a `stdscr' sin definir
/usr/bin/ld: /home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:37: referencia a `stdscr' sin definir
/usr/bin/ld: /home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:37: referencia a `stdscr' sin definir
/usr/bin/ld: /home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:37: referencia a `stdscr' sin definir
/usr/bin/ld: HelloWorldEngine.o: en la función `Renderer::Renderer(int)':
/home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:45: referencia a `stdscr' sin definir
/usr/bin/ld: HelloWorldEngine.o:/home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:45: más referencias a `stdscr' sin definir a continuación
/usr/bin/ld: HelloWorldEngine.o: en la función `Renderer::load_curses()':
/home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:65: referencia a `initscr' sin definir
/usr/bin/ld: /home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:66: referencia a `noecho' sin definir
/usr/bin/ld: /home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:67: referencia a `cbreak' sin definir
/usr/bin/ld: /home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:68: referencia a `curs_set' sin definir
/usr/bin/ld: /home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:69: referencia a `stdscr' sin definir
/usr/bin/ld: /home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:69: referencia a `nodelay' sin definir
/usr/bin/ld: /home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:70: referencia a `stdscr' sin definir
/usr/bin/ld: /home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:70: referencia a `keypad' sin definir
/usr/bin/ld: /home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:71: referencia a `use_default_colors' sin definir
/usr/bin/ld: /home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:72: referencia a `start_color' sin definir
/usr/bin/ld: /home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:73: referencia a `init_pair' sin definir
/usr/bin/ld: /home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:74: referencia a `init_pair' sin definir
/usr/bin/ld: /home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:75: referencia a `init_pair' sin definir
/usr/bin/ld: /home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:76: referencia a `init_pair' sin definir
/usr/bin/ld: /home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:77: referencia a `init_pair' sin definir
/usr/bin/ld: HelloWorldEngine.o:/home/edgar/Hello-World-Engine/HelloWorldEngine.cpp:78: más referencias a `init_pair' sin definir a continuación
`

**Comment by CodigoLasagna** [comment]
de acuerdo, cuando se postea un problema, necesito especificaciones de tu equipo, tales como sistema operativo, que version de mingw estas tratando de usar así como la versión de ncurses de tu sistema.

**Comment by Naraku86** [comment]
Saludos.
Estoy tratando desde Linux, Ubuntu 20.04
la versión de gcc
`gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
`
Version de ncurses, es la versión 6.2.20200212

**Comment by CodigoLasagna** [comment]
estas tratando de llamar el motor/librería desde un archivo main(?, el makefile esta para compilar un archivo main que cargue el motor, si estas usando la misma estructura de archivos de todo el proyecto, todo debería de funcionar, si no es el caso, te recomiendo que te lleves el motor a una carpeta a parte (el .cpp y el .h), hagas un main.cpp y trates de compilar las 3 cosas juntas, puedes intentar usando el archivo .cpp dentro de la carpeta template.
el motor no es un un programa, es una herramienta/librería, así que no va a funcionar por si sola, de ultimo recurso puedes intentar compilar agregando `-ltinfo` al makefile o a una linea de compilación propia, a veces sucede que ncurses se divide en más de una librería al momento de compilar.

**Comment by CodigoLasagna** [comment]
Ojo, el makefile no es de uso obligatorio, te recomiendo que intentes ante todo compilar las cosas sin el, solo esta ahí para facilitar las cosas, pero no es lo único que podría funcionar.
algo tan simple como lo siguiente debería de funcionar:
 `g++ snake/snake.cpp HelloWorldEngine.cpp -lncurses -lpanel -o main` 
Es un ejemplo para compilar el proyecto de snake dentro de la carpeta raíz donde se encuentra la librería.

**Comment by Naraku86** [comment]
ya me compilo, y se ejecuto el snake, creo que te falta documentar mejor como probar el proyecto y las funciones de tu libriria/engine.

Suerte.
![image](https://user-images.githubusercontent.com/10275851/177918824-d6497ed6-53cc-4741-9aab-b025c5cdb6ac.png)
![image](https://user-images.githubusercontent.com/10275851/177919221-2e39bb26-86b8-463e-9c81-5983654873e2.png)
